name: Build and push Docker image on this

on:
  push:
    branches: [main, master]

env:
  IMAGE_NAME: my-flask-app
  REGISTRY_NAME: testinggitaction

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          DOCKER_PASSWORD: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
